# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-11 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beio_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_top', 'rank', '-published_date', '-created_date'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='context',
        ),
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
    ]
