# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-24 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeioUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱地址')),
                ('date_of_birth', models.DateField(verbose_name='邮箱地址')),
                ('createdate', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('img', models.CharField(default='/static/images/tx/default.jpg', max_length=200, verbose_name='头像地址')),
                ('intro', models.CharField(blank=True, max_length=200, null=True, verbose_name='简介')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
