# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-24 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beio_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beiouser',
            name='date_of_birth',
        ),
    ]
