# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-24 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beio_auth', '0004_auto_20170924_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='beiouser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
