# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-24 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beio_auth', '0005_beiouser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beiouser',
            name='createdate',
        ),
    ]
