# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-24 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('beio_auth', '0006_remove_beiouser_createdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beiouser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='beiouser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 9, 24, 6, 37, 56, 246560, tzinfo=utc), verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='beiouser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
