# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-24 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beio_auth', '0008_auto_20170924_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beiouser',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='beiouser',
            name='img',
            field=models.FileField(default='/static/images/tx/default.jpg', max_length=200, upload_to='/static/images/tx/', verbose_name='头像地址'),
        ),
    ]
