# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beio_auth', '0009_auto_20170924_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beiouser',
            name='img',
            field=models.ImageField(default='/tx/default.jpg', max_length=200, upload_to='/tx/', verbose_name='头像地址'),
        ),
    ]
