# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-04 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beio_auth', '0010_auto_20170924_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beiouser',
            name='img',
            field=models.CharField(default='/media/tx/default.jpg', max_length=200, verbose_name='头像地址'),
        ),
        migrations.AlterField(
            model_name='beiouser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
